import { defaultStyles, defaultTitle } from '@/constants';
import { clone } from '@core/utils';

const presetState = {
  ['new']: {
    title: defaultTitle,
    rowState: {},
    colState: {},
    dataState: {},
    stylesState: {},
    currentText: '',
    currentStyles: defaultStyles,
    openedData: new Date().toJSON(),
  },
  ['intro']: {
    title: 'Моя таблица',
    colState: {
      '0': 189,
      '1': 36,
      '2': 35,
      '3': 36,
      '4': 27,
      '5': 30,
      '6': 29,
      '7': 25,
    },
    dataState: {
      '0:0': 'Привет  Excel',
      '0:1': '08',
      '0:2': '06',
      '0:3': '2021',
      '0:8': '=(2*45)-35/5',
      '1:0': '',
      '2:0': '',
      '2:1': 'Пн',
      '2:2': 'Вт',
      '2:3': 'Ср',
      '2:4': 'Чт',
      '2:5': 'Пт',
      '2:6': 'Сб',
      '2:7': 'Вс',
      '3:0': '1',
      '3:1': '31',
      '3:2': '1',
      '3:3': '2',
      '3:4': '3',
      '3:5': '4',
      '3:6': '5',
      '3:7': '6',
      '4:0': '2',
      '4:1': '7',
      '4:2': '8',
      '4:3': '9',
      '4:4': '10',
      '4:5': '11',
      '4:6': '12',
      '4:7': '13',
      '5:0': '3',
      '5:1': '14',
      '5:2': '15',
      '5:3': '16',
      '5:4': '17',
      '5:5': '18',
      '5:6': '19',
      '5:7': '20',
      '6:0': '4',
      '6:1': '21',
      '6:2': '22',
      '6:3': '23',
      '6:4': '24',
      '6:5': '25',
      '6:6': '26',
      '6:7': '27',
      '7:0': '5',
      '7:1': '28',
      '7:2': '29',
      '7:3': '30',
      '7:4': '',
    },
    rowState: {'1': 26},
    stylesState: {
      '0:0': {fontWeight: 'bold', textAlign: 'center', fontStyle: 'italic', textDecoration: 'underline'},
      '0:1': {textAlign: 'center', fontWeight: 'normal', fontStyle: 'italic', textDecoration: 'underline'},
      '0:2': {fontStyle: 'italic', textDecoration: 'underline', textAlign: 'center'},
      '0:3': {fontStyle: 'italic', textDecoration: 'underline', textAlign: 'center'},
      '1:0': {textAlign: 'right', fontWeight: 'bold'},
      '2:0': {textAlign: 'center', fontWeight: 'bold'},
      '2:1': {fontWeight: 'bold', textAlign: 'center'},
      '2:2': {fontWeight: 'bold', textAlign: 'center'},
      '2:3': {fontWeight: 'bold', textAlign: 'center'},
      '2:4': {fontWeight: 'bold', textAlign: 'center'},
      '2:5': {fontWeight: 'bold', textAlign: 'center'},
      '2:6': {fontWeight: 'bold', textAlign: 'center'},
      '2:7': {fontWeight: 'bold', textAlign: 'center'},
      '3:0': {fontWeight: 'bold', textAlign: 'right'},
      '3:1': {fontStyle: 'italic', textAlign: 'center'},
      '3:2': {fontStyle: 'italic', textAlign: 'center'},
      '3:3': {fontStyle: 'italic', textAlign: 'center'},
      '3:4': {fontStyle: 'italic', textAlign: 'center'},
      '3:5': {fontStyle: 'italic', textAlign: 'center'},
      '3:6': {fontStyle: 'italic', textAlign: 'center'},
      '3:7': {fontStyle: 'italic', textAlign: 'center'},
      '4:0': {textAlign: 'right', fontWeight: 'bold'},
      '4:1': {fontStyle: 'italic', textAlign: 'center'},
      '4:2': {fontStyle: 'italic', textAlign: 'center'},
      '4:3': {fontStyle: 'italic', textAlign: 'center'},
      '4:4': {fontStyle: 'italic', textAlign: 'center'},
      '4:5': {fontStyle: 'italic', textAlign: 'center'},
      '4:6': {fontStyle: 'italic', textAlign: 'center'},
      '4:7': {fontStyle: 'italic', textAlign: 'center'},
      '5:0': {textAlign: 'right', fontWeight: 'bold'},
      '5:1': {fontStyle: 'italic', textAlign: 'center'},
      '5:2': {fontStyle: 'italic', textAlign: 'center'},
      '5:3': {fontStyle: 'italic', textAlign: 'center'},
      '5:4': {fontStyle: 'italic', textAlign: 'center'},
      '5:5': {fontStyle: 'italic', textAlign: 'center'},
      '5:6': {fontStyle: 'italic', textAlign: 'center'},
      '5:7': {fontStyle: 'italic', textAlign: 'center'},
      '6:0': {textAlign: 'right', fontWeight: 'bold'},
      '6:1': {fontStyle: 'italic', textAlign: 'center'},
      '6:2': {fontStyle: 'italic', textAlign: 'center'},
      '6:3': {fontStyle: 'italic', textAlign: 'center'},
      '6:4': {fontStyle: 'italic', textAlign: 'center'},
      '6:5': {fontStyle: 'italic', textAlign: 'center'},
      '6:6': {fontStyle: 'italic', textAlign: 'center'},
      '6:7': {fontStyle: 'italic', textAlign: 'center'},
      '7:0': {textAlign: 'right', fontWeight: 'bold'},
      '7:1': {fontStyle: 'italic', textAlign: 'center'},
      '7:2': {fontStyle: 'italic', textAlign: 'center'},
      '7:3': {fontStyle: 'italic', textAlign: 'center'},
      '7:4': {fontStyle: 'italic', textAlign: 'center'},
      '7:5': {fontStyle: 'italic', textAlign: 'center'},
      '7:6': {fontStyle: 'italic', textAlign: 'center'},
      '7:7': {fontStyle: 'italic', textAlign: 'center'},
    },
    openedData: new Date().toJSON(),
    currentStyles: defaultStyles,
    currentText: '',
  },
};

const normalize = (state) => ({
  ...state,
  currentStyles: defaultStyles,
  currentText: '',
});

export function normalizeInitialState(state, preset = 'new') {
  if (state) {
    return normalize(state);
  } else {
    return clone(presetState[preset]);
  }
}
